package minor;


import java.awt.BorderLayout;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;
import minor.Bill;
import minor.DBconnection;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author dell
 */
public class NewJDialog extends javax.swing.JDialog {

    /**
     * Creates new form NewJDialog
     */
    DBconnection db = new DBconnection();

    DefaultTableModel model1 = new DefaultTableModel();
    JTable table1 = new JTable(model1);

    public NewJDialog(Bill parent, boolean modal) {
        super(parent, modal);
        initComponents();
        try {

            model1.addColumn("Item number");
            model1.addColumn("Item name");
            model1.addColumn("Price");
            model1.addColumn("Quantity");
            model1.addColumn("Amount");

            PreparedStatement ps = db.cn.prepareStatement("select * from bill where Tablenumber=?");
            ps.setString(1, parent.txttablenumber.getText());
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                model1.addRow(new Object[]{rs.getString(1), rs.getString(2), rs.getString(3), rs.getString(4), rs.getString(5)});
            }
            ps.close();
            db.cn.close();
            int v = ScrollPaneConstants.VERTICAL_SCROLLBAR_AS_NEEDED;
            int h = ScrollPaneConstants.HORIZONTAL_SCROLLBAR_AS_NEEDED;
            JScrollPane scrollPane = new JScrollPane(table1, v, h);
            add(scrollPane);
            scrollPane.setBounds(0, 0, 600, 400);
            
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
        setSize(600, 400);
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
